CREATE TABLE kohteet.katualueenosa_paatos (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    katualueenosa_id INTEGER NOT NULL REFERENCES kohteet.katualueenosa(id) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED,
    paatos_id INTEGER NOT NULL REFERENCES kohteet.paatos(id) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED,
    UNIQUE (katualueenosa_id, paatos_id)
);

CREATE TABLE kohteet.paatos_liite (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    paatos_id INTEGER NOT NULL REFERENCES kohteet.paatos(id) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED,
    liite_id INTEGER NOT NULL REFERENCES kohteet.liite(id) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED,
    UNIQUE (paatos_id, liite_id)
);

ALTER TABLE kohteet.katualueenosa
    DROP COLUMN paatostieto_id;

ALTER TABLE kohteet.paatos
    DROP COLUMN liitetieto_id;
