DELETE FROM kohteet.varustemateriaali;
INSERT INTO kohteet.varustemateriaali (id, selite) OVERRIDING SYSTEM VALUE VALUES (1, 'betoni');
INSERT INTO kohteet.varustemateriaali (id, selite) OVERRIDING SYSTEM VALUE VALUES (2, 'elementtiverkko');
INSERT INTO kohteet.varustemateriaali (id, selite) OVERRIDING SYSTEM VALUE VALUES (3, 'kaksipuolinen teräspalkki');
INSERT INTO kohteet.varustemateriaali (id, selite) OVERRIDING SYSTEM VALUE VALUES (4, 'kivi');
INSERT INTO kohteet.varustemateriaali (id, selite) OVERRIDING SYSTEM VALUE VALUES (5, 'lasikuitu');
INSERT INTO kohteet.varustemateriaali (id, selite) OVERRIDING SYSTEM VALUE VALUES (6, 'metalli');
INSERT INTO kohteet.varustemateriaali (id, selite) OVERRIDING SYSTEM VALUE VALUES (7, 'muovi');
INSERT INTO kohteet.varustemateriaali (id, selite) OVERRIDING SYSTEM VALUE VALUES (8, 'panssariverkko');
INSERT INTO kohteet.varustemateriaali (id, selite) OVERRIDING SYSTEM VALUE VALUES (9, 'putkipalkki');
INSERT INTO kohteet.varustemateriaali (id, selite) OVERRIDING SYSTEM VALUE VALUES (10, 'puu');
INSERT INTO kohteet.varustemateriaali (id, selite) OVERRIDING SYSTEM VALUE VALUES (11, 'teräs');
INSERT INTO kohteet.varustemateriaali (id, selite) OVERRIDING SYSTEM VALUE VALUES (12, 'teräspalkki');
INSERT INTO kohteet.varustemateriaali (id, selite) OVERRIDING SYSTEM VALUE VALUES (13, 'teräsverkko');
INSERT INTO kohteet.varustemateriaali (id, selite) OVERRIDING SYSTEM VALUE VALUES (14, 'vaijeri');
INSERT INTO kohteet.varustemateriaali (id, selite) OVERRIDING SYSTEM VALUE VALUES (15, 'valurauta');
INSERT INTO kohteet.varustemateriaali (id, selite) OVERRIDING SYSTEM VALUE VALUES (16, 'muu');
INSERT INTO kohteet.varustemateriaali (id, selite) OVERRIDING SYSTEM VALUE VALUES (17, 'ei tiedossa');
SELECT setval(pg_get_serial_sequence('kohteet.varustemateriaali', 'id'), (select max(id) from kohteet.varustemateriaali));
